### ISSUE TITLE
differential on analog input hangs

### ISSUE THREAD

**Issue by mklomp** [MrYsLab/Telemetrix4RpiPico#15]
When running the [analog_input.py](https://github.com/MrYsLab/tmx-pico-aio/blob/master/examples/analog_input.py) example while setting the differential to 0, the datastream will hang after a couple of seconds. No data comes in. When doing the same thing without the regular (non-AIO) version, I get an error of None Type.

**Comment by MrYsLab** [comment]
@mklomp You are probably aware of this, but the example will print analog input for 5 seconds, disables analog input reporting for 3 seconds, and finally re-enables reporting.

I ran the following example for several minutes on the asyncio client and did something similar for the non-asyncio client, and I do not see the issue. 
```

import asyncio
import sys
import time

from tmx_pico_aio import tmx_pico_aio

"""
Monitor the Pico internal temperature sensor (ADC 4) and return raw values.
"""

# Set up a pin for analog input and monitor its changes
ADC = 4  # temperature sensor ADC

# Callback data indices
CB_PIN_MODE = 0
CB_PIN = 1
CB_VALUE = 2
CB_TIME = 3


# noinspection GrazieInspection
async def the_callback(data):
    """
    A callback function to report data changes.
    This will print the pin number, its reported value and
    the date and time when the differential is exceeded
    :param data: [report_type, ADC#, current reported value, timestamp]
    """
    date = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(data[CB_TIME]))
    print(f'ADC Report Type: {data[CB_PIN_MODE]} ADC: {data[CB_PIN]} '
          f'Value: {data[CB_VALUE]} Time Stamp: {date}')


async def analog_in(my_board, adc):
    # noinspection GrazieInspection
    """
         This function establishes the pin as an
         analog input. Any changes on this pin will
         be reported through the call back function.

         :param my_board: a pymata4 instance
         :param adc: ADC number
         """

    # set the pin mode
    await my_board.set_pin_mode_analog_input(adc, differential=0, callback=the_callback)

    print('Enter Control-C to quit.')
    try:
        # await asyncio.sleep(5)
        # print('Disabling reporting for 3 seconds.')
        # await my_board.disable_analog_reporting(adc)
        # await asyncio.sleep(3)
        # print('Re-enabling reporting.')
        # await my_board.enable_analog_reporting(adc)
        while True:
            await asyncio.sleep(5)
    except KeyboardInterrupt:
        await my_board.shutdown()
        sys.exit(0)

# get the event loop
loop = asyncio.get_event_loop()
try:
    board = tmx_pico_aio.TmxPicoAio()
except KeyboardInterrupt:
    sys.exit()

try:
    # start the main function
    loop.run_until_complete(analog_in(board, ADC))
    loop.run_until_complete(board.reset_board())
except KeyboardInterrupt:
    loop.run_until_complete(board.shutdown())
    sys.exit(0)
except RuntimeError:
    sys.exit(0)

```

**Comment by mklomp** [comment]
Hi @MrYsLab. Excuses for not being clear on the fact that the original example indeed has the behaviour you described. My first test was also uncommenting that behaviour with nothing connected to the pins (same as the example you attached).

I took a bit more time do dive into it, and it turns out I am running into the CPU limitations of my SBC (Orange Pi Zero). With differential set to 0 (or even 1 or 2) the CPU has too high load and (on the non AIO version) will hang with error:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/telemetrix_rpi_pico/telemetrix_rpi_pico.py", line 1675, in _reporter
    dispatch_entry(response_data)
TypeError: 'NoneType' object is not callable
```
Like you, I was unable to reproduce this on my laptop (with a more decent CPU ;)). When running telemetrix4arduino on this  same SBC I also run into CPU issues (when setting differential to 0), but this results in buffering issues (which I kind of expect). I am therefore not expecting this behaviour. Again: on non-AIO I get the error above, on AIO-version I just get no new data.

**Comment by MrYsLab** [comment]
To check if it is a slow CPU issue, I tested using an RPi 3B and set CPU utilization to 10% using the cpulimit utility. The reported issue could not be reproduced. Therefore, the problem may be due to overwhelming the UART on the OrangePi Zero.

I have created a new branch called scan_delay that adds a delay of 20ms after all inputs are scanned. The .uf2 may be downloaded using [this link](https://github.com/MrYsLab/Telemetrix4RpiPico/raw/scan_delay/cmake-build-release/Telemetrix4RpiPico.uf2).

Please try the .uf2 image and let me know if it solves it.

**Comment by mklomp** [comment]
Hi @MrYsLab, thanks for the new branch. This indeed makes the script not crash anymore. But of course it does limit the update frequency to 50Hz. Just as a benchmark: when running the [analog example](https://github.com/MrYsLab/telemetrix-aio/blob/1.2/examples/analog_input2.py) (please note it was release 1.2, but still) on the OrangePi Zero using an arduino nano (and telemetrix-aio and setting differential to 0) I do get an update frequency of around 750Hz. So to me that seems to be the highest throughput the UART from the OrangePi Zero could get. And in that example the set_analog_scan_interval is set to 0 (which is not in the Pico version). So I would say that the Pico version should be able to got up to 750Hz as well.

**Comment by MrYsLab** [comment]
@mklomp I will update the new branch to allow the delay to be settable via a command on the Python asyncio side, also with its own branch. The range would be from a zero ms delay (the default) up to 255 ms.

I'll let you know when it's available. I expect it to be complete by the weekend.

**Comment by MrYsLab** [comment]
It took less time than I initially thought. Update the pico with [this .uf2](https://github.com/MrYsLab/Telemetrix4RpiPico/raw/scan_delay/cmake-build-release/Telemetrix4RpiPico.uf2). 

In the [scan_delay branch of tmx-pico-aio](https://github.com/MrYsLab/tmx-pico-aio/tree/scan_delay),  there is an [example demonstrating changing the delay dynamically](https://github.com/MrYsLab/tmx-pico-aio/blob/scan_delay/examples/analog_input_variable_delay.py).

**Comment by mklomp** [comment]
Hi @MrYsLab , perfect! I tested it and indeed works. It all works with a delay of 1ms giving me a update frequency of around 850Hz.  Did not check any latency issues, but assume they will be similar to the nano's. Also tested with a delay of 0, and indeed still hangs.

**Comment by MrYsLab** [comment]
@mklomp I will leave this issue open, and I plan to merge the branch if I need to make any additional changes to the pico files (python and C-SDK). 

Is using the branch an acceptable solution for your needs for now?

Thanks.

**Comment by mklomp** [comment]
Prefect. Works for me.
